# ================================
# HTTP -> HTTPS
# ================================
server {
  listen 80;
  server_name sap.lab.sr.bnc.ch;
  return 301 https://$host$request_uri;
}

# ================================
# HTTPS (self-signed)
# ================================
server {
  listen 443 ssl;
  server_name sap.lab.sr.bnc.ch;

  ssl_certificate     /etc/nginx/certs/sap.lab.sr.bnc.ch.crt;
  ssl_certificate_key /etc/nginx/certs/sap.lab.sr.bnc.ch.key;

  ssl_protocols TLSv1.2 TLSv1.3;

  proxy_set_header Host              $host;
  proxy_set_header X-Real-IP         $remote_addr;
  proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location / {
    proxy_pass http://sap-app:3000;
  }
}
